apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcc-products
  labels:
    app: pcc-products
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pcc-products
  template:
    metadata:
      labels:
        app: pcc-products
    spec:
      containers:
        - name: pcc-products
          image: diogojms/pcc_products:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://DriveCleaner:DriveCleanerG7@cluster0.bj3pzfe.mongodb.net/Products"
            - name: SECRET
              value: "jfcnbjsnwdelwjcnewdlejbsfew"
            - name: LOGS_URI
              value: "guest:guest@localhost:5672/"
