apiVersion: v1
kind: Service
metadata:
  name: pcc-products
  labels:
    app: pcc-products
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    app: pcc-products
  sessionAffinity: None
